<!DOCTYPE html>
<html lang="en"><head>
<script src="gc_files/libs/clipboard/clipboard.min.js"></script>
<script src="gc_files/libs/quarto-html/tabby.min.js"></script>
<script src="gc_files/libs/quarto-html/popper.min.js"></script>
<script src="gc_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="gc_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="gc_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="gc_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Jia Guo, Mattias Blum, Jinxiang Ma, Noah Kochanski">
  <title>Group Challenge</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="gc_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="gc_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="gc_files/libs/revealjs/dist/theme/quarto-8f3eebe07241f08526c91a7e9cbef8fd.css">
  <link href="gc_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="gc_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="gc_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="gc_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Group Challenge</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Jia Guo, Mattias Blum, Jinxiang Ma, Noah Kochanski 
</div>
</div>
</div>

</section>
<section>
<section id="group-challenge-1" class="title-slide slide level1 center">
<h1>Group Challenge 1</h1>

</section>
<section id="dhs" class="slide level2">
<h2>DHS</h2>
<p>Our data comes from the <a href="https://dhsprogram.com">Demographic Health Survey Program</a>.</p>
<ul>
<li>The Demographic Health Survey (DHS) is a national level survey conducted in many countries around the globe.</li>
<li>DHS collects and distributes a plethora of data on aspects of developing nations.</li>
</ul>
</section>
<section id="dhs-1" class="slide level2">
<h2>DHS</h2>
<ul>
<li><p>Our particular analysis will be conducted on the <strong>birth</strong> related survey from 2017-2018 in Bangladesh.</p></li>
<li><p>For this survey, households were sampled in particular clusters (villages or town centers) around the country.</p></li>
<li><p>If a mother was surveyed in a particular cluster location, they were asked if they had any children under the age of <strong>5</strong>. If they did, then a particular question was about their children under the age of 5.</p></li>
<li><p>For this particular survey, 2383 observations (births) were recorded across Bangladesh.</p></li>
</ul>
</section>
<section id="analysis-of-covariates---summary-of-main-dataset-and-cluster-metadata" class="slide level2">
<h2>Analysis of Covariates - Summary of Main Dataset and Cluster Metadata</h2>
<p>The main dataset contains 29 covariates. One of these covariates is cluster_id, a unique numeric key identifying a site of measurement. Another dataset contains metadata pertaining to each individual cluster, detailing:</p>
<ul>
<li><p>Geographic location (latitude, longitude)</p></li>
<li><p>ID for the DHS survey</p></li>
<li><p>Year of the survey</p></li>
<li><p>Coordinate reference system (CRS: WGS84)</p></li>
</ul>
</section>
<section id="analysis-of-covariates---summary-of-main-dataset-and-cluster-metadata-1" class="slide level2">
<h2>Analysis of Covariates - Summary of Main Dataset and Cluster Metadata</h2>
<p>Although none of the metadata fields will be used for analysis, we must join on cluster_id to recover geographic locations.</p>
</section>
<section id="household-and-demographic-variables" class="slide level2">
<h2>Household and Demographic Variables</h2>
<ul>
<li>Cluster ID from DHS data<br>
</li>
<li>Household number within the cluster<br>
</li>
<li>Rank of individual within household<br>
</li>
<li>Number of household members<br>
</li>
<li>Number of children under 5 in household<br>
</li>
<li>Gender of household head</li>
</ul>
</section>
<section id="household-and-demographic-variables-1" class="slide level2">
<h2>Household and Demographic Variables</h2>
<ul>
<li>Urban or rural residence<br>
</li>
<li>Wealth index category<br>
</li>
<li>Survey weighting variable<br>
</li>
<li>Stratification variable for survey design<br>
</li>
<li>PSU identifier for survey design</li>
</ul>
</section>
<section id="maternal-variables" class="slide level2">
<h2>Maternal Variables</h2>
<ul>
<li>Age of the mother<br>
</li>
<li>Education level of the mother<br>
</li>
<li>Occupation type<br>
</li>
<li>Mother’s height (cm)<br>
</li>
<li>Mother’s BMI<br>
</li>
<li>Marital status of the mother<br>
</li>
<li>Number of antenatal visits attended<br>
</li>
<li>Diagnosed with high blood pressure<br>
</li>
<li>Diagnosed with diabetes</li>
</ul>
</section>
<section id="child-variables" class="slide level2">
<h2>Child Variables</h2>
<ul>
<li>Birth order of the child<br>
</li>
<li>Sex of child<br>
</li>
<li>Source of birth weight measurement<br>
</li>
<li>Birth weight in grams<br>
</li>
<li>Categorized birth weight<br>
</li>
<li>Date of birth</li>
</ul>
</section>
<section id="household-infrastructure-variables" class="slide level2">
<h2>Household Infrastructure Variables</h2>
<ul>
<li>Type of drinking water source<br>
</li>
<li>Type of toilet facility<br>
</li>
<li>Availability of electricity<br>
</li>
<li>Floor material<br>
</li>
<li>Type of cooking fuel</li>
</ul>
<!-- ## Analysis of Covariates - Household and Demographic Variables -->
<!-- | Variable Name         | Description                                 | -->
<!-- |-----------------------|---------------------------------------------| -->
<!-- | clusterid             | Cluster ID from DHS data                    | -->
<!-- | household_number      | Household number within the cluster         | -->
<!-- | household_rank        | Rank of individual within household         | -->
<!-- | household_members     | Number of household members                 | -->
<!-- | household_under_5     | Number of children under 5 in household     | -->
<!-- | household_head        | Gender of household head ("male", "female") | -->
<!-- | type_of_residence     | Urban or rural residence ("urban", "rural") | -->
<!-- | wealth_index          | Wealth index category                       | -->
<!-- | survey_weight         | Survey weighting variable                   | -->
<!-- | strata                | Stratification variable for survey design   | -->
<!-- | primary_sampling_unit | PSU identifier for survey design            | -->
<!-- ## Analysis of Covariates - Maternal Variables -->
<!-- | Variable Name | Description | -->
<!-- |---------------------------------------------|---------------------------| -->
<!-- | mother_current_age | Age of the mother | -->
<!-- | mother_education | Education level of the mother ("No education", "Primary", "Secondary or Higher") | -->
<!-- | mother_occupation | Occupation type ("Manual labor", "Not working or non manual") | -->
<!-- | mother_height | Mother's height (in cm) | -->
<!-- | mother_bmi | Mother's BMI | -->
<!-- | mother_marital_status | Marital status of the mother ("married/partnered", "no partner") | -->
<!-- | antenatal_visits | Number of antenatal visits attended | -->
<!-- | mother_hbp | Diagnosed with high blood pressure (Yes/No) | -->
<!-- | mother_diabetes | Diagnosed with diabetes (Yes/No) | -->
<!-- ## Analysis of Covariates - Child Variables -->
<!-- | Variable Name | Description | -->
<!-- |--------------------------------------------|----------------------------| -->
<!-- | birth_order | Birth order of the child | -->
<!-- | sex_of_child | Sex of child ("male", "female") | -->
<!-- | birth_weight_type | Source of birth weight measurement ("mother recall", "written card") | -->
<!-- | birth_weight | Birth weight in grams (NA if missing) | -->
<!-- | birth_weight_cat | Categorized birth weight ("low" \< 2500g, "normal" 2500-4000g, "high" \> 4000g) | -->
<!-- | birth_date | Date of birth (YYYY-MM-DD) | -->
<!-- ## Analysis of Covariates - Household Infrastructure Variables -->
<!-- | Variable Name | Description | -->
<!-- |------------------------------------------------|------------------------| -->
<!-- | household_water | Type of drinking water source (1 = "Improved", 0 = "Unimproved") | -->
<!-- | household_toilet | Type of toilet facility ("Flush toilet", "Pit latrine", "No facility", "Other") | -->
<!-- | household_electricity | Availability of electricity ("Yes", "No") | -->
<!-- | household_floor | Floor material (1 = "Finished", 0 = "Unfinished") | -->
<!-- | household_cooking_fuel | Type of cooking fuel (1 = "Clean", 0 = "Non clean") | -->
</section>
<section id="analysis-of-covariates---pairwise-correlation-of-numeric-variables" class="slide level2">
<h2>Analysis of Covariates - Pairwise Correlation of Numeric Variables</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-4-1.png" width="960" class="r-stretch"></section>
<section id="analysis-of-covariates---variance-inflation-factor" class="slide level2">
<h2>Analysis of Covariates - Variance Inflation Factor</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        household_rank     mother_current_age        household_water 
              2.555389               1.983368               1.009798 
     household_members      household_under_5 household_cooking_fuel 
              2.615649               1.213228               1.747282 
         mother_height             mother_bmi           wealth_index 
              1.069034               1.248646               1.765605 
           birth_order       antenatal_visits           birth_weight 
              2.011993               1.090437               1.030285 
         survey_weight                 strata  primary_sampling_unit 
              1.552240              31.586843              32.943293 </code></pre>
</div>
</div>
</section>
<section id="analysis-of-covariates---autocorrelation" class="slide level2">
<h2>Analysis of Covariates - Autocorrelation</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-6-1.png" width="960" class="r-stretch"></section>
<section id="spatial-domain" class="slide level2">
<h2>Spatial Domain</h2>
<ul>
<li>The study covers <strong>Bangladesh</strong>, with observations from <strong>2,383 participants</strong> distributed across geographic coordinates (latitude and longitude).<br>
</li>
<li>Each participant’s location was masked by assigning them to a <strong>cluster centroid</strong> (via <code>clusterid</code>).<br>
</li>
<li>To create pseudo-unique locations, small <strong>i.i.d. Gaussian noise</strong> (SD = 0.001 degrees) was added to latitude/longitude.<br>
</li>
<li>Observations are <strong>spatially indexed</strong> using these randomized coordinates.</li>
</ul>
</section>
<section id="spatial-dependence" class="slide level2">
<h2>Spatial Dependence</h2>
<ul>
<li><strong>Covariance decay with distance</strong> is a reasonable assumption due to spatial dependence of birth weight on environmental factors (e.g., local temperature).<br>
</li>
<li><strong>Spatial correlation</strong> may arise from:
<ul>
<li>Shared environmental exposures (e.g., regional climate, pollution).<br>
</li>
<li>Socioeconomic conditions that vary geographically.<br>
</li>
</ul></li>
<li>Using <strong>distance-based covariance</strong> assumes that <strong>mothers in close proximity experience similar environmental influences</strong> affecting birth outcomes.</li>
</ul>
</section>
<section id="empirical-variogram" class="slide level2">
<h2>Empirical Variogram</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-7-1.png" width="960" class="r-stretch"></section>
<section id="empirical-variogram-1" class="slide level2">
<h2>Empirical Variogram</h2>
<p>The empirical variogram for birth weight displays three key features:</p>
<ol type="1">
<li>A decrease in semivariance at very short distances (&lt;20 km), likely reflecting the artificial noise added to cluster centroids. This “dip” represents reduced variability within clusters due to the imposed randomization, as participants from the same original cluster are now treated as spatially distinct but still share similar environmental conditions.</li>
</ol>
</section>
<section id="empirical-variogram-2" class="slide level2">
<h2>Empirical Variogram</h2>
<ol start="2" type="1">
<li><p>An increasing trend between 20–80 km, indicating spatial dependence. Rising semivariance with distance suggests that birth weights become less similar as geographic separation increases, consistent with spatial autocorrelation.</p></li>
<li><p>A plateau beyond 80 km, implying the spatial correlation range (where covariance stabilizes) is reached.</p></li>
</ol>
</section>
<section id="empirical-variogram-3" class="slide level2">
<h2>Empirical Variogram</h2>
<p>Overall, the spatial pattern aligns with the hypothesis that environmental factors like temperature—which vary regionally—may contribute to geographic disparities in birth weight. Further investigation into the covariance structure and model diagnostics would strengthen these conclusions.</p>
</section>
<section id="cluster-locations" class="slide level2">
<h2>Cluster Locations</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-10-1.png" width="960" class="r-stretch"></section>
<section id="wealth-index" class="slide level2">
<h2>Wealth Index</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-12-1.png" width="960" class="r-stretch"></section>
<section id="wealth-index-1" class="slide level2">
<h2>Wealth Index</h2>
<p>The data shows both large-scale trends (visible in heat maps) and local variation Urban-rural differences create discontinuities in the spatial pattern River systems in Bangladesh might create natural boundaries/corridors for spatial correlation The jittering adds some noise to the spatial relationships but shouldn’t significantly affect large-scale patterns</p>
</section>
<section id="birth-weight" class="slide level2">
<h2>Birth Weight</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-13-1.png" width="960" class="r-stretch"></section>
<section id="maternal-education" class="slide level2">
<h2>Maternal Education</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-14-1.png" width="960" class="r-stretch"></section>
<section id="household-water-access" class="slide level2">
<h2>Household Water Access</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-15-1.png" width="960" class="r-stretch"></section>
<section id="residence-type-and-birth-weight" class="slide level2">
<h2>Residence Type and Birth Weight</h2>

<!-- ## Wealth Index -->
<!-- ```{r} -->
<!-- library(ggplot2) -->
<!-- library(scico)   -->
<!-- ggplot() + -->
<!--   geom_hex(data = birth_imp, -->
<!--            aes(x = LONG_jitter, y = LAT_jitter, z = wealth_index), -->
<!--            bins = 20,  -->
<!--            stat = "summary_hex", -->
<!--            fun = mean) + -->
<!--   geom_sf(data = bangladesh, fill = NA, color = "white", size = 0.8) + -->
<!--   scale_fill_viridis_c(name = "Wealth\nIndex") + -->
<!--   theme_minimal() + -->
<!--   labs(title = "Wealth Index Distribution in Bangladesh", -->
<!--        x = "Longitude",  -->
<!--        y = "Latitude") + -->
<!--   coord_sf() -->
<!-- ``` -->
<!-- ### what is the spatial domain, its dimension, how are observations indexed in space? -->
<!-- #### Spatial Domain: -->
<!-- The study covers Bangladesh, which spans approximately: Latitude: 21°N to 26°N Longitude: 88°E to 92°E The domain is a single contiguous region bounded by natural features -->
<!-- #### Spatial Indexing: -->
<!-- Data is collected at DHS cluster locations (clusterid) Each observation is geolocated using: Original coordinates (LAT, LONG) Jittered coordinates (LAT_jitter, LONG_jitter) with Gaussian noise (sd = 0.001) The jittering was added for privacy/confidentiality of exact locations -->
<!-- #### Spatial Structure: -->
<!-- ```{r} -->
<!-- # Calculate empirical variogram -->
<!-- variog <- variogram(birth_weight ~ 1, birth_projected, width = 20000) -->
<!-- plot(variog, main = "Empirical Variogram of Birth Weight", -->
<!--      xlab = "Distance (m)", ylab = "Semivariance", -->
<!--      pch = 19, col = "blue",  -->
<!--      ylim = c(450000, 525000)) -->
<!-- ``` -->
<!-- The empirical variogram shows: Clear spatial dependence Semivariance increases with distance: Range appears to be around 100-150km There's a notable nugget effect (non-zero y-intercept) -->
<!-- #Do you think modeling covariance as decaying with distance is appropriate?: Yes, modeling covariance as decaying with distance is appropriate here because: Birth weights show clear spatial clustering in our visualization There are likely underlying spatial factors affecting birth weight: Healthcare access varies geographically Socioeconomic conditions cluster spatially Environmental factors (pollution, water quality) have spatial patterns Cultural practices and dietary habits often show regional patterns -->
<img data-src="gc_files/figure-revealjs/unnamed-chunk-16-1.png" width="960" class="r-stretch"></section>
<section id="possible-research-questions" class="slide level2">
<h2>Possible Research Questions</h2>
<p>How do birth weights vary between urban and rural areas in Bangladesh? Is there a relationship between household wealth and birth weight outcomes? Do regions with better water access show improved birth weight outcomes? How does mother’s education level correlate with birth weight across different regions?</p>
</section>
<section id="possible-research-questions-1" class="slide level2">
<h2>Possible Research Questions</h2>
<p>Are there distinct regional clusters of high/low birth weights? Do coastal regions show different patterns compared to inland areas? Is there evidence of spillover effects from urban centers to surrounding rural areas? How do major river systems influence the spatial distribution of birth weights?</p>
</section>
<section id="possible-research-questions-2" class="slide level2">
<h2>Possible Research Questions</h2>
<p>How strongly does wealth index predict birth weight when controlling for spatial correlation? Is the relationship between mother’s education and birth weight consistent across regions? Do areas with better infrastructure (water access, healthcare facilities) show more consistent birth weights</p>
</section>
<section id="references" class="slide level2">
<h2>References</h2>
<p>National Institute of Population Research and Training (NIPORT), and ICF. (2020).&nbsp;<em>Bangladesh Demographic and Health Survey 2017-18</em>. Dhaka, Bangladesh, and Rockville, Maryland, USA: NIPORT and ICF.</p>
</section></section>
<section>
<section id="group-challenge-2" class="title-slide slide level1 center">
<h1>Group Challenge 2</h1>

</section>
<section id="loading-data" class="slide level2 smaller">
<h2>Loading Data</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a>birth_imp <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">'data/input/birth_imp.RDS'</span>) <span class="co"># Load the imputed birth data</span></span>
<span id="cb2-2"><a href=""></a>cluster_locations <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'data/input/cluster_locations.csv'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href=""></a>  <span class="fu">rename</span>(<span class="at">clusterid =</span> DHSCLUST) <span class="sc">%&gt;%</span> </span>
<span id="cb2-4"><a href=""></a>  <span class="fu">select</span>(clusterid, LATNUM, LONGNUM)</span>
<span id="cb2-5"><a href=""></a>reg_data <span class="ot">&lt;-</span> <span class="fu">left_join</span>(birth_imp, cluster_locations)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The dataset birth_imp.RDS contains birth-related data. Another dataset, cluster_locations.csv, contains spatial information about clusters, including latitude (LATNUM) and longitude (LONGNUM). The column DHSCLUST is renamed to clusterid to maintain consistency across datasets, and only relevant columns are selected.</p>
<p>The two datasets are merged using left_join(), ensuring that birth-related records are matched with their corresponding cluster locations based on the clusterid field.</p>
</section>
<section id="standard-linear-regression" class="slide level2 smaller">
<h2>Standard Linear Regression</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = birth_weight ~ birth_weight_type + mother_bmi + 
    sex_of_child + mother_current_age, data = reg_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-2342.4  -457.1    12.6   467.6  3239.3 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   2653.29795   90.88762  29.193  &lt; 2e-16 ***
birth_weight_typewritten card  -89.92422   71.37700  -1.260 0.207848    
mother_bmi                       0.16857    0.03512   4.800 1.69e-06 ***
sex_of_childmale               106.70534   28.71063   3.717 0.000207 ***
mother_current_age              -4.52190    2.74553  -1.647 0.099689 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 698.4 on 2378 degrees of freedom
Multiple R-squared:  0.01605,   Adjusted R-squared:  0.01439 
F-statistic: 9.695 on 4 and 2378 DF,  p-value: 8.905e-08</code></pre>
</div>
</div>
</section>
<section id="standard-linear-regression-1" class="slide level2 smaller">
<h2>Standard Linear Regression</h2>
<p>The linear regression model explains a small portion of the variance in birth weight, with a coefficient of determination of 0.016, indicating that the included predictors only account for about 1.6% of the variation. The low coefficient of determination suggests that additional factors, possibly spatial or environmental variables, may be influencing birth weight.</p>
<p>The intercept, 2653 grams, represents the estimated birth weight for a female child, with an unspecified birth weight type, and at average maternal BMI and age. Mother BMI has a significant positive effect on birth weight, 0.17 grams per unit increase, suggesting that higher BMI is associated with heavier newborns.</p>
<p>Male children weigh about 107 grams more than females on average. The effect of mother age is negative, 4.52 grams decrease per year, but not statistically significant at the 5% level, implying weak evidence for an age-related decline in birth weight.</p>
<p>The variable birth weight type (written card vs.&nbsp;mother recall) has an estimated difference of -90 grams but is not statistically significant, indicating no strong evidence that recorded birth weight type impacts the outcome.</p>
</section>
<section id="residual-visualization" class="slide level2 smaller">
<h2>Residual Visualization</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-19-1.png" width="960" class="r-stretch"></section>
<section id="residual-visualization-1" class="slide level2 smaller">
<h2>Residual Visualization</h2>
<p>This scatter plot visualizes the residuals from the linear regression model across spatial coordinates (LATNUM and LONGNUM). Each point represents a geographic location, and the color gradient indicates the magnitude of the residuals. Yellow/Green regions represent positive residuals, where the model underestimates birth weight. Blue/Purple regions represent negative residuals, where the model overestimates birth weight. Near-zero residuals (mid-range colors) indicate areas where the model’s predictions are more accurate. Base on this scatter plot, clusters of similar residual values (e.g., regions where residuals are predominantly positive or negative) suggest that there is a spatial correlation in the errors. This indicates that the linear model may not fully account for spatial dependencies in the data.</p>
</section>
<section id="empirical-variogram-4" class="slide level2 smaller">
<h2>Empirical Variogram</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-20-1.png" width="960" class="r-stretch"></section>
<section id="empirical-variogram-5" class="slide level2 smaller">
<h2>Empirical Variogram</h2>
<p>The empirical variogram of residuals reveals the spatial dependence structure of unexplained variation after fitting the linear model. The increasing trend in semivariance at short distances (within 50 kilometers) suggests positive spatial autocorrelation, indicating that residuals from nearby locations tend to be similar. The lack of a clear sill suggests that spatial dependence persists beyond the observed range or that non-stationarity may be present. Fluctuations in the variogram could be due to noise, uneven spatial sampling, or anisotropy in the spatial process.</p>
</section>
<section id="bayesian-regression" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<h3 id="preparing-data">Preparing Data</h3>
<div class="sourceCode" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a>X <span class="ot">&lt;-</span> reg_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(birth_weight_type, mother_bmi, sex_of_child, mother_current_age) <span class="sc">%&gt;%</span> <span class="fu">as.matrix</span>()</span>
<span id="cb4-2"><a href=""></a>y <span class="ot">&lt;-</span> reg_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(birth_weight) <span class="sc">%&gt;%</span> <span class="fu">as.matrix</span>()</span>
<span id="cb4-3"><a href=""></a>p <span class="ot">&lt;-</span> <span class="fu">ncol</span>(X)</span>
<span id="cb4-4"><a href=""></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The predictor variables are extracted into a matrix X, while the response variable birth_weight is stored in a separate matrix y. The number of predictors is assigned to p, and the total number of observations is stored in n.</p>
<h3 id="add-random-noise-to-coordinates">Add Random Noise to Coordinates</h3>
<div class="sourceCode" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>coords <span class="ot">&lt;-</span> cluster_locations <span class="sc">%&gt;%</span> <span class="fu">select</span>(LATNUM, LONGNUM) </span>
<span id="cb5-2"><a href=""></a>coords <span class="ot">&lt;-</span> coords <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="at">n =</span> p<span class="sc">*</span>n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Random noise is added to the coordinates of each cluster. This slight perturbation ensures that spatial locations are not exactly identical</p>
</section>
<section id="bayesian-regression-1" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<h3 id="intialize-mcmc">Intialize MCMC</h3>
<div class="sourceCode" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a>n.samples <span class="ot">&lt;-</span> <span class="dv">2000</span> <span class="co"># Number of MCMC iterations</span></span>
<span id="cb6-2"><a href=""></a>starting <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"phi"</span><span class="ot">=</span><span class="dv">3</span><span class="sc">/</span><span class="fl">0.5</span>, <span class="st">"sigma.sq"</span><span class="ot">=</span><span class="dv">50</span>, <span class="st">"tau.sq"</span><span class="ot">=</span><span class="dv">1</span>) <span class="co"># Inital Value for MCMC</span></span>
<span id="cb6-3"><a href=""></a>tuning <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"phi"</span><span class="ot">=</span><span class="fl">0.1</span>, <span class="st">"sigma.sq"</span><span class="ot">=</span><span class="fl">0.1</span>, <span class="st">"tau.sq"</span><span class="ot">=</span><span class="fl">0.1</span>) <span class="co"># Defining Tuning Parameters</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The number of samples for the Markov Chain Monte Carlo (MCMC) process is set to 2000. This controls how many iterations the Bayesian inference process will perform to estimate spatial relationships. For initial values, the parameter phi controls the range of spatial correlation, sigma.sq represents the variance of the spatial process, and tau.sq captures small-scale variability or measurement noise. Tuning parameters determine the step sizes used in the MCMC algorithm. Proper tuning ensures efficient sampling and improves convergence.</p>
</section>
<section id="bayesian-regression-2" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<h3 id="prior-distribution-covariance-model">Prior Distribution &amp; Covariance model</h3>
<div class="sourceCode" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a>priors<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"beta.Norm"</span><span class="ot">=</span><span class="fu">list</span>(<span class="fu">rep</span>(<span class="dv">0</span>,p), <span class="fu">diag</span>(<span class="dv">1000</span>,p)),</span>
<span id="cb7-2"><a href=""></a>                 <span class="st">"phi.Unif"</span><span class="ot">=</span><span class="fu">c</span>(<span class="fl">0.1</span>, <span class="dv">3</span><span class="sc">/</span><span class="fl">0.1</span>), </span>
<span id="cb7-3"><a href=""></a>                 <span class="st">"sigma.sq.IG"</span><span class="ot">=</span><span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>),</span>
<span id="cb7-4"><a href=""></a>                 <span class="st">"tau.sq.IG"</span><span class="ot">=</span><span class="fu">c</span>(<span class="dv">2</span>, <span class="fl">0.1</span>))</span>
<span id="cb7-5"><a href=""></a>cov.model <span class="ot">&lt;-</span> <span class="st">"exponential"</span>                 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Prior distributions are assigned to model parameters. The regression coefficients (beta.Norm) follow a normal distribution centered at zero with high variance. The spatial range parameter (phi) has a uniform prior. The variances (sigma.sq and tau.sq) follow inverse-gamma distributions, ensuring positive values while allowing flexibility.</p>
<p>The covariance structure is set to an exponential model, where spatial correlation decays exponentially with distance. This choice assumes that nearby locations are more strongly correlated than distant ones.</p>
</section>
<section id="bayesian-regression-3" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<div class="sourceCode" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a>n.report <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb8-2"><a href=""></a>verbose <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb8-3"><a href=""></a></span>
<span id="cb8-4"><a href=""></a>m<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">spLM</span>(y<span class="sc">~</span>X, <span class="at">coords=</span><span class="fu">as.matrix</span>(coords), <span class="at">starting=</span>starting,</span>
<span id="cb8-5"><a href=""></a>           <span class="at">tuning=</span>tuning, <span class="at">priors=</span>priors<span class="fl">.1</span>, <span class="at">cov.model=</span>cov.model,</span>
<span id="cb8-6"><a href=""></a>           <span class="at">n.samples=</span>n.samples, <span class="at">verbose=</span>verbose, <span class="at">n.report=</span>n.report)</span>
<span id="cb8-7"><a href=""></a></span>
<span id="cb8-8"><a href=""></a><span class="fu">summary</span>(m<span class="fl">.1</span><span class="sc">$</span>p.theta.samples) <span class="co">#Summarize Posterior Distribution</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Iterations = 1:5000
Thinning interval = 1 
Number of chains = 1 
Sample size per chain = 5000 

1. Empirical mean and standard deviation for each variable,
   plus standard error of the mean:

              Mean        SD  Naive SE Time-series SE
sigma.sq 7.543e+05 9.280e+04 1.312e+03      1.418e+04
tau.sq   6.797e-02 8.232e-02 1.164e-03      9.566e-03
phi      2.963e+01 1.539e+00 2.177e-02      2.414e-01

2. Quantiles for each variable:

              2.5%       25%       50%       75%     97.5%
sigma.sq 7.113e+05 7.492e+05 7.652e+05 7.770e+05 8.156e+05
tau.sq   2.384e-02 3.920e-02 5.048e-02 6.893e-02 1.926e-01
phi      2.651e+01 2.978e+01 2.992e+01 2.995e+01 2.998e+01</code></pre>
</div>
</div>
</section>
<section id="bayesian-regression-4" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<p>The posterior estimates from the spatial Bayesian linear model (spLM) indicate strong spatial dependence in birth weight variations. The posterior mean for the spatial variance (sigma.sq = 754,300) suggests that a significant portion of the variability is explained by spatial factors, with a relatively narrow credible interval ([711,300, 815,600]), confirming stability in the estimates. The nugget variance (tau.sq = 0.068), representing measurement error or unstructured variability, is relatively low, suggesting minimal noise in the observations. The range parameter (phi ≈ 29.63), with a tight 95% credible interval ([26.51, 29.98]), indicates a strong spatial correlation, meaning birth weights in locations within this range exhibit similar trends.</p>
</section>
<section id="bayesian-regression-5" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<h3 id="mcmc-results---trace-plot-of-spatial-process-parameter---φ">MCMC Results - Trace Plot of Spatial Process Parameter - Φ</h3>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-30-1.png" width="960" class="r-stretch"></section>
<section id="bayesian-regression-6" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<h3 id="mcmc-results---trace-plot-of-spatial-process-parameters---σ²">MCMC Results - Trace Plot of Spatial Process Parameters - σ²</h3>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-31-1.png" width="960" class="r-stretch"></section>
<section id="bayesian-regression-7" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<h3 id="mcmc-results---trace-plot-of-spatial-process-parameters---τ²">MCMC Results - Trace Plot of Spatial Process Parameters - τ²</h3>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-32-1.png" width="960" class="r-stretch"></section>
<section id="bayesian-regression-8" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<h3 id="analysis-of-trace-plots">Analysis of Trace Plots</h3>
<p>The trace plots for key spatial process parameters (Φ, σ², τ²) flatten out after around 300 iterations. This indicates that the MCMC chain has likely converged to the posterior distribution after the initial burn-in period. The first 300 iterations are considered burn-in, and the subsequent iterations reflect the true posterior. Additionally, the chains exhibit no trends or systematic movements, suggesting effective exploration of the parameter space.</p>
</section>
<section id="bayesian-regression-9" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<h3 id="mcmc-results---autocorrelation-of-spatial-process-parameter---φ">MCMC Results - Autocorrelation of Spatial Process Parameter - Φ</h3>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-33-1.png" width="960" class="r-stretch"></section>
<section id="bayesian-regression-10" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<h3 id="mcmc-results---autocorrelation-of-spatial-process-parameter---σ²">MCMC Results - Autocorrelation of Spatial Process Parameter - σ²</h3>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-34-1.png" width="960" class="r-stretch"></section>
<section id="bayesian-regression-11" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<h3 id="mcmc-results---autocorrelation-of-spatial-process-parameter---τ²">MCMC Results - Autocorrelation of Spatial Process Parameter - τ²</h3>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-35-1.png" width="960" class="r-stretch"></section>
<section id="bayesian-regression-12" class="slide level2 smaller">
<h2>Bayesian Regression</h2>
<h3 id="analysis-of-autocorrelation-plots">Analysis of Autocorrelation Plots</h3>
<p>The autocorrelation plots for Φ and σ² show similar trends, with both parameters exhibiting a slow decay in autocorrelation, indicating moderate dependence between successive samples. This suggests reasonable mixing for these parameters. However, for τ², the autocorrelation decays to a lower value of 0.25, indicating slower mixing and stronger dependence between samples. This slower decay for τ² suggests the chain may be struggling to effectively explore the parameter space for this parameter, potentially due to strong correlations with other parameters or insufficient mixing.</p>
</section></section>
<section>
<section id="group-challenge-3" class="title-slide slide level1 center">
<h1>Group Challenge 3</h1>

</section>
<section id="jittering" class="slide level2 smaller">
<h2>Jittering</h2>
<p>Formal Jittering. We set for 0.03 as standard deviation.</p>

<img data-src="gc_files/figure-revealjs/map-1.png" width="960" class="r-stretch"></section>
<section id="regression" class="slide level2 smaller">
<h2>Regression</h2>
<p>We run a linear model with the 4 covariates for future initial parameters setting.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ ., data = X_selected_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-2342.4  -457.1    12.6   467.6  3239.3 

Coefficients:
                           Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              2563.37373  114.97376  22.295  &lt; 2e-16 ***
birth_weight_type_recall   89.92422   71.37700   1.260 0.207848    
mother_bmi                  0.16857    0.03512   4.800 1.69e-06 ***
sex_of_child_male         106.70534   28.71063   3.717 0.000207 ***
mother_current_age         -4.52190    2.74553  -1.647 0.099689 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 698.4 on 2378 degrees of freedom
Multiple R-squared:  0.01605,   Adjusted R-squared:  0.01439 
F-statistic: 9.695 on 4 and 2378 DF,  p-value: 8.905e-08</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>B₀: 89.924, B1: 0.169, B2: 106.705, B3: -4.522</code></pre>
</div>
</div>
</section>
<section id="mgp-trace-and-density-plots-for-regression-coefficients-β1" class="slide level2 smaller">
<h2>MGP Trace and Density Plots for Regression Coefficients (β1)</h2>

<img data-src="gc_files/figure-revealjs/plot-1.png" width="960" class="r-stretch"></section>
<section id="mgp-trace-and-density-plots-for-regression-coefficients-β2" class="slide level2 smaller">
<h2>MGP Trace and Density Plots for Regression Coefficients (β2)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-36-1.png" width="960" class="r-stretch"></section>
<section id="mgp-trace-and-density-plots-for-regression-coefficients-β3" class="slide level2 smaller">
<h2>MGP Trace and Density Plots for Regression Coefficients (β3)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-37-1.png" width="960" class="r-stretch"></section>
<section id="mgp-trace-and-density-plots-for-regression-coefficients-β4" class="slide level2 smaller">
<h2>MGP Trace and Density Plots for Regression Coefficients (β4)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-38-1.png" width="960" class="r-stretch"></section>
<section id="mgp-trace-and-density-plots-for-hyperparameters-τ²" class="slide level2 smaller">
<h2>MGP Trace and Density Plots for Hyperparameters (τ²)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-39-1.png" width="960" class="r-stretch"></section>
<section id="mgp-trace-and-density-plots-for-hyperparameters-φ" class="slide level2 smaller">
<h2>MGP Trace and Density Plots for Hyperparameters (φ)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-40-1.png" width="960" class="r-stretch"></section>
<section id="mgp-trace-and-density-plots-for-hyperparameters-σ²" class="slide level2 smaller">
<h2>MGP Trace and Density Plots for Hyperparameters (σ²)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-41-1.png" width="960" class="r-stretch"></section>
<section id="mgp-trace-and-density-plots---analysis" class="slide level2">
<h2>MGP Trace and Density Plots - Analysis</h2>
<p>The convergence is reached after approximately 6,000 iterations, so we ran for 28,000 iterations and burn the first 8,000. We initialize the regression coefficients (<span class="math inline">\(\beta\)</span>) from the linear regression with the covariates we are interested in.</p>
</section>
<section id="posterior-predictive-map" class="slide level2 smaller">
<h2>Posterior Predictive Map</h2>

<img data-src="gc_files/figure-revealjs/prediction-1.png" width="960" class="r-stretch"></section>
<section id="empirical-spatial-variogram" class="slide level2 smaller">
<h2>Empirical Spatial Variogram</h2>

<img data-src="gc_files/figure-revealjs/variogram-1.png" width="960" class="r-stretch"></section>
<section id="nonspatial-linear-regression" class="slide level2 smaller">
<h2>Nonspatial Linear Regression</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = birth_weight ~ birth_weight_type + mother_bmi + 
    sex_of_child + mother_current_age, data = reg_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-2342.4  -457.1    12.6   467.6  3239.3 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   2653.29795   90.88762  29.193  &lt; 2e-16 ***
birth_weight_typewritten card  -89.92422   71.37700  -1.260 0.207848    
mother_bmi                       0.16857    0.03512   4.800 1.69e-06 ***
sex_of_childmale               106.70534   28.71063   3.717 0.000207 ***
mother_current_age              -4.52190    2.74553  -1.647 0.099689 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 698.4 on 2378 degrees of freedom
Multiple R-squared:  0.01605,   Adjusted R-squared:  0.01439 
F-statistic: 9.695 on 4 and 2378 DF,  p-value: 8.905e-08</code></pre>
</div>
</div>
</section>
<section id="spatial-nearest-neighbor-gaussian-process" class="slide level2 smaller">
<h2>Spatial Nearest Neighbor Gaussian Process</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>----------------------------------------
    Building the neighbor list
----------------------------------------</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>----------------------------------------
Building the neighbors of neighbors list
----------------------------------------</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>----------------------------------------
    Model description
----------------------------------------
NNGP Latent model fit with 2383 observations.

Number of covariates 5 (including intercept if specified).

Using the exponential spatial correlation model.

Using 15 nearest neighbors.

Number of MCMC samples 2000.

Priors and hyperpriors:
    beta flat.
    sigma.sq IG hyperpriors shape=2.00000 and scale=1.00000
    tau.sq IG hyperpriors shape=2.00000 and scale=1.00000
    phi Unif hyperpriors a=3.00000 and b=30.00000


Source not compiled with OpenMP support.
----------------------------------------
        Sampling
----------------------------------------
Sampled: 100 of 2000, 5.00%
Report interval Metrop. Acceptance rate: 57.00%
Overall Metrop. Acceptance rate: 57.00%
-------------------------------------------------
Sampled: 200 of 2000, 10.00%
Report interval Metrop. Acceptance rate: 81.00%
Overall Metrop. Acceptance rate: 69.00%
-------------------------------------------------
Sampled: 300 of 2000, 15.00%
Report interval Metrop. Acceptance rate: 66.00%
Overall Metrop. Acceptance rate: 68.00%
-------------------------------------------------
Sampled: 400 of 2000, 20.00%
Report interval Metrop. Acceptance rate: 77.00%
Overall Metrop. Acceptance rate: 70.25%
-------------------------------------------------
Sampled: 500 of 2000, 25.00%
Report interval Metrop. Acceptance rate: 63.00%
Overall Metrop. Acceptance rate: 68.80%
-------------------------------------------------
Sampled: 600 of 2000, 30.00%
Report interval Metrop. Acceptance rate: 72.00%
Overall Metrop. Acceptance rate: 69.33%
-------------------------------------------------
Sampled: 700 of 2000, 35.00%
Report interval Metrop. Acceptance rate: 87.00%
Overall Metrop. Acceptance rate: 71.86%
-------------------------------------------------
Sampled: 800 of 2000, 40.00%
Report interval Metrop. Acceptance rate: 69.00%
Overall Metrop. Acceptance rate: 71.50%
-------------------------------------------------
Sampled: 900 of 2000, 45.00%
Report interval Metrop. Acceptance rate: 65.00%
Overall Metrop. Acceptance rate: 70.78%
-------------------------------------------------
Sampled: 1000 of 2000, 50.00%
Report interval Metrop. Acceptance rate: 67.00%
Overall Metrop. Acceptance rate: 70.40%
-------------------------------------------------
Sampled: 1100 of 2000, 55.00%
Report interval Metrop. Acceptance rate: 59.00%
Overall Metrop. Acceptance rate: 69.36%
-------------------------------------------------
Sampled: 1200 of 2000, 60.00%
Report interval Metrop. Acceptance rate: 42.00%
Overall Metrop. Acceptance rate: 67.08%
-------------------------------------------------
Sampled: 1300 of 2000, 65.00%
Report interval Metrop. Acceptance rate: 48.00%
Overall Metrop. Acceptance rate: 65.62%
-------------------------------------------------
Sampled: 1400 of 2000, 70.00%
Report interval Metrop. Acceptance rate: 60.00%
Overall Metrop. Acceptance rate: 65.21%
-------------------------------------------------
Sampled: 1500 of 2000, 75.00%
Report interval Metrop. Acceptance rate: 65.00%
Overall Metrop. Acceptance rate: 65.20%
-------------------------------------------------
Sampled: 1600 of 2000, 80.00%
Report interval Metrop. Acceptance rate: 60.00%
Overall Metrop. Acceptance rate: 64.88%
-------------------------------------------------
Sampled: 1700 of 2000, 85.00%
Report interval Metrop. Acceptance rate: 74.00%
Overall Metrop. Acceptance rate: 65.41%
-------------------------------------------------
Sampled: 1800 of 2000, 90.00%
Report interval Metrop. Acceptance rate: 73.00%
Overall Metrop. Acceptance rate: 65.83%
-------------------------------------------------
Sampled: 1900 of 2000, 95.00%
Report interval Metrop. Acceptance rate: 78.00%
Overall Metrop. Acceptance rate: 66.47%
-------------------------------------------------
Sampled: 2000 of 2000, 100.00%
Report interval Metrop. Acceptance rate: 62.00%
Overall Metrop. Acceptance rate: 66.25%
-------------------------------------------------</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
spNNGP(formula = birth_weight ~ birth_weight_type + mother_bmi + 
    sex_of_child + mother_current_age, data = reg_data, coords = coords, 
    method = "latent", n.neighbors = 15, starting = starting, 
    tuning = tuning, priors = priors, cov.model = cov.model, 
    n.samples = n.samples, n.omp.threads = 4, return.neighbor.info = TRUE, 
    fit.rep = TRUE, sub.sample = list(start = burn_in + 1, thin = thin_val))

Model class is NNGP, method latent, family gaussian.

Model object contains 2000 MCMC samples.

Chain sub.sample:
start = 1000
end = 2000
thin = 1
samples size = 1001
                              2.5%        25%         50%         75%        
(Intercept)                   2465.8234   2589.3557   2652.2175   2711.6499  
birth_weight_typewritten card -222.6849   -131.6917   -85.9321    -39.8576   
mother_bmi                    0.1038      0.1462      0.1713      0.1936     
sex_of_childmale              52.8149     87.5137     107.4503    126.9807   
mother_current_age            -9.7638     -6.4262     -4.4589     -2.6049    
sigma.sq                      186.6622    210.1165    227.7529    256.8892   
tau.sq                        460974.9390 477274.3627 486555.3655 497041.3538
phi                           17.3649     20.2631     22.5814     25.0871    
                              97.5%      
(Intercept)                   2818.3560  
birth_weight_typewritten card 45.7286    
mother_bmi                    0.2402     
sex_of_childmale              163.6529   
mother_current_age            0.5645     
sigma.sq                      326.3804   
tau.sq                        513818.2239
phi                           27.7145    </code></pre>
</div>
</div>
</section>
<section id="nngp-trace-and-density-plots-for-regression-coefficients-β1" class="slide level2 smaller">
<h2>NNGP Trace and Density Plots for Regression Coefficients (β1)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-45-1.png" width="960" class="r-stretch"></section>
<section id="nngp-trace-and-density-plots-for-regression-coefficients-β2" class="slide level2 smaller">
<h2>NNGP Trace and Density Plots for Regression Coefficients (β2)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-46-1.png" width="960" class="r-stretch"></section>
<section id="nngp-trace-and-density-plots-for-regression-coefficients-β3" class="slide level2 smaller">
<h2>NNGP Trace and Density Plots for Regression Coefficients (β3)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-47-1.png" width="960" class="r-stretch"></section>
<section id="nngp-trace-and-density-plots-for-regression-coefficients-β4" class="slide level2 smaller">
<h2>NNGP Trace and Density Plots for Regression Coefficients (β4)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-48-1.png" width="960" class="r-stretch"></section>
<section id="nngp-trace-and-density-plots-for-regression-coefficients-β5" class="slide level2 smaller">
<h2>NNGP Trace and Density Plots for Regression Coefficients (β5)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-49-1.png" width="960" class="r-stretch"></section>
<section id="nngp-trace-and-density-plots-for-regression-coefficients-β---analysis" class="slide level2 smaller">
<h2>NNGP Trace and Density Plots for Regression Coefficients (β) - Analysis</h2>
<p>The trace plots for the <span class="math inline">\(\beta\)</span> parameters illustrate that after an initial burn-in period the chains stabilize and fluctuate around a fixed mean, indicating good mixing and convergence. Corresponding density plots show smooth, unimodal distributions for each coefficient, which suggests that the posterior estimates for the fixed effects are reliable</p>
</section>
<section id="nngp-trace-and-density-plots-for-hyperparameters-φ" class="slide level2 smaller">
<h2>NNGP Trace and Density Plots for Hyperparameters (φ)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-50-1.png" width="960" class="r-stretch"></section>
<section id="nngp-trace-and-density-plots-for-hyperparameters-σ²" class="slide level2 smaller">
<h2>NNGP Trace and Density Plots for Hyperparameters (σ²)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-51-1.png" width="960" class="r-stretch"></section>
<section id="nngp-trace-and-density-plots-for-hyperparameters-τ²" class="slide level2 smaller">
<h2>NNGP Trace and Density Plots for Hyperparameters (τ²)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-52-1.png" width="960" class="r-stretch"></section>
<section id="nngp-trace-and-density-plots-for-hyperparameters---analysis" class="slide level2 smaller">
<h2>NNGP Trace and Density Plots for Hyperparameters - Analysis</h2>
<p>For the spatial decay parameter (φ) and variance components (σ² for the spatial process and τ² for the nugget), the trace plots demonstrate that the chains converge after a burn-in period. The density plots reveal that although φ exhibits some right skew (with a long tail), all hyperparameters exhibit unimodal posterior distributions. This indicates that the model has successfully explored the parameter space and reached a stable posterior distribution.</p>
</section>
<section id="trace-and-density-plots-for-selected-latent-spatial-effects-w1131" class="slide level2 smaller">
<h2>Trace and Density Plots for Selected Latent Spatial Effects (w(1131))</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-53-1.png" width="960" class="r-stretch"></section>
<section id="trace-and-density-plots-for-selected-latent-spatial-effects-w397" class="slide level2 smaller">
<h2>Trace and Density Plots for Selected Latent Spatial Effects (w(397))</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-54-1.png" width="960" class="r-stretch"></section>
<section id="trace-and-density-plots-for-selected-latent-spatial-effects-w318" class="slide level2 smaller">
<h2>Trace and Density Plots for Selected Latent Spatial Effects (w(318))</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-55-1.png" width="960" class="r-stretch"></section>
<section id="trace-and-density-plots-for-selected-latent-spatial-effects-w266" class="slide level2 smaller">
<h2>Trace and Density Plots for Selected Latent Spatial Effects (w(266))</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-56-1.png" width="960" class="r-stretch"></section>
<section id="trace-and-density-plots-for-selected-latent-spatial-effects-w1354" class="slide level2 smaller">
<h2>Trace and Density Plots for Selected Latent Spatial Effects (w(1354))</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-57-1.png" width="960" class="r-stretch"></section>
<section id="trace-and-density-plots-for-selected-latent-spatial-effects---analysis" class="slide level2 smaller">
<h2>Trace and Density Plots for Selected Latent Spatial Effects - Analysis</h2>
<p>The trace plots for the latent spatial effect w(s) at selected locations show stable fluctuations over the MCMC iterations, with no evident trends or abrupt jumps, which confirms convergence. Their density plots, while showing some variability across locations, are generally smooth and unimodal. This implies that the spatial random effects are well‐estimated at the individual locations.</p>
</section>
<section id="posterior-predictive-map-at-observed-locations" class="slide level2 smaller">
<h2>Posterior Predictive Map at Observed Locations</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-59-1.png" width="960" class="r-stretch"></section>
<section id="posterior-predictive-map-at-observed-locations-1" class="slide level2 smaller">
<h2>Posterior Predictive Map at Observed Locations</h2>
<p>This map displays the posterior predictive distribution for the observed locations, derived from one selected draw (or the posterior mean) of the y_rep samples. The color scale represents the predicted birth weight values. The relatively uniform distribution of colors (without large-scale gradients) suggests that the NNGP model has effectively accounted for spatial variation in the observed response</p>
</section>
<section id="empirical-variogram-of-posterior-predictive-values" class="slide level2 smaller">
<h2>Empirical Variogram of Posterior Predictive Values</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-60-1.png" width="960" class="r-stretch"></section>
<section id="residuals-variogram-of-posterior-predictive-values" class="slide level2 smaller">
<h2>Residuals Variogram of Posterior Predictive Values</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-61-1.png" width="960" class="r-stretch"></section>
<section id="residuals-variogram-of-posterior-predictive-values-1" class="slide level2 smaller">
<h2>Residuals Variogram of Posterior Predictive Values</h2>
<p>The variogram of the model residuals displays a moderate increase at medium distances before leveling off. This pattern indicates that while most of the spatial dependence has been accounted for by the model, some minor spatial correlation remains among nearby observations. However, the overall level of semivariance does not continue to increase with distance, which supports the conclusion that the residual spatial autocorrelation is weak and likely due to random variability rather than a systematic bias. We see the sharp drop of semivariance when distance is greater than 200, this is due to the limited data at large distance.</p>
</section>
<section id="estimated-latent-process-ws" class="slide level2 smaller">
<h2>Estimated Latent Process w(s)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-62-1.png" width="960" class="r-stretch"></section>
<section id="estimated-latent-process-ws-1" class="slide level2 smaller">
<h2>Estimated Latent Process w(s)</h2>
<p>The map clearly illustrates the spatial heterogeneity in the latent field, highlighting areas where the model detects higher or lower spatial effects. This visualization helps in interpreting the spatial structure that the NNGP model has captured beyond what is explained by the covariates.</p>
</section>
<section id="empirical-variogram-of-the-estimated-latent-process-ws" class="slide level2 smaller">
<h2>Empirical Variogram of the Estimated Latent Process w(s)</h2>

<img data-src="gc_files/figure-revealjs/unnamed-chunk-63-1.png" width="960" class="r-stretch"></section>
<section id="empirical-variogram-of-the-estimated-latent-process-ws-1" class="slide level2 smaller">
<h2>Empirical Variogram of the Estimated Latent Process w(s)</h2>
<p>The latent spatial process w(s) exhibits some small-scale variability near neighboring locations, causing the semivariance to be unexpectedly high at very short lags. As distance increases, the semivariance declines and fluctuates, indicating that the spatial correlation in w(s) is relatively short-ranged.</p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="gc_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="gc_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="gc_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="gc_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="gc_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="gc_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="gc_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="gc_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="gc_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="gc_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

       // Parallax background image
       parallaxBackgroundImage: 'assets/background.png', // e.g. "'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg'"

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>